pipeline{
    agent any
    
    stages{
        stage('git checkout'){
            steps{
                echo "Cloning the code"
                git branch:"master",url:"https://github.com/twinklefornewtech/Amazon.git"
            }
        }
        stage('Build for SpringDemo'){
            steps{
                dir('SpringDemo'){
                    echo "Generating Build for SpringDemo..."
                    sh "mvn clean install"
                }
            }
        }
    }
    post{
        success{
            dir('SpringDemo/target'){
                echo "SpringDemo.jar generated..."
                //sh 'curl -u admin:admin123 -T Amazon.war "http://localhost:8081/manager/text/deploy?path=/hookapp&update=true"'
            }
        }
        failure{
            echo "SpringDemo Build failed"
        }
    }
}
