pipeline{
    agent any
    
    stages{
        stage('git checkout'){
            steps{
                echo "Cloning the code"
                git branch:"master",url:"https://github.com/twinklefornewtech/Amazon.git"
            }
        }
        stage('Build for SpringCore'){
            steps{
                dir('SpringCore'){
                    echo "Generating Build for SpringCore..."
                    sh "mvn clean install"
                }
            }
        }
    }
    post{
        success{
            dir('SpringCore/target'){
                echo "SpringCore.jar generated"
                //sh 'curl -u admin:admin123 -T Amazon.war "http://localhost:8081/manager/text/deploy?path=/hookapp&update=true"'
            }
        }
        failure{
            echo "SpringCore Build failed"
        }
    }
}
