pipeline{
    agent any
    
    stages{
        stage('git checkout'){
            steps{
                echo "Cloning the code"
                git branch:"master",url:"https://github.com/twinklefornewtech/Amazon.git"
            }
        }
        stage('Build for SpringNew'){
            steps{
                dir('SpringNew'){
                    echo "Generating Build for SpringNew..."
                    sh "mvn clean install"
                }
            }
        }
    }
    post{
        success{
            dir('SpringNew/Spring-Web/target'){
                echo "Deploying SpringNew to tomcat..."
                sh 'curl -u admin:admin123 -T SpringNew.war "http://localhost:8081/manager/text/deploy?path=/SpringNew&update=true"'
            }
        }
        failure{
            echo "SpringNew Build failed"
        }
    }
}
