pipeline{
    agent any
    
    stages{
        stage('git checkout'){
            steps{
                echo "Cloning the code"
                //git branch:"master",url:"https://github.com/twinklefornewtech/Amazon.git"
            }
        }
        stage('Build for SKY'){
            steps{
                dir('SKY'){
                    echo "Generating Build for SKY..."
                    sh "mvn clean install"
                }
            }
        }
    }
    post{
        success{
            dir('SKY/SKY-Web/target'){
                echo "Deploying to tomcat..."
                sh 'curl -u admin:admin123 -T SKY.war "http://localhost:8081/manager/text/deploy?path=/SKY&update=true"'
            }
        }
        failure{
            echo "SKY Build failed"
        }
    }
}
